[package]
name = "accel"
version = "0.1.0"
authors = ["eloylp <eloylp@eloylp.dev>"]
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
hal = { workspace = true }
esp-backtrace = { workspace = true }
esp-println = { workspace = true }
icm42670 = "0.1.1"
